version: "3.9"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/app/data
      - ./data/mitre_attack.db:/app/data/mitre_attack.db:ro

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  backend-data:
